import Foundation

/// A stored `OnboardRide` pinned to the indices of one particular `Timetable`.
///
/// Short-lived on purpose: pattern and trip indices belong to the snapshot they were resolved
/// against, and a snapshot is rebuilt on every reimport and every anchor day. Nothing persists
/// one of these.
public struct ResolvedOnboardRide: Sendable, Hashable {
    public let pattern: Int
    public let trip: Int
    public let currentPosition: Int
    /// Signed, positive is late. Carried from the ride, not recomputed here.
    public let delaySeconds: Int32

    public init(pattern: Int, trip: Int, currentPosition: Int, delaySeconds: Int32) {
        self.pattern = pattern; self.trip = trip
        self.currentPosition = currentPosition; self.delaySeconds = delaySeconds
    }
}

/// Finds a stored ride again in a freshly built timetable.
///
/// Called on every plan and every position update, because the timetable the ride was declared
/// against may already be gone: `GTFSFeedService` reimports weekly, `TimetableStore` builds a
/// new snapshot per anchor day, and both renumber every pattern and trip. What survives is the
/// ride's *fingerprint* — its line and its ordered stop sequence — which is why `OnboardRide`
/// stores that instead of an index.
public enum OnboardRideResolution {

    public enum Failure: Error, Sendable, Hashable {
        /// The line no longer has a pattern with this shape. A reimport reshaped the route.
        case patternGone(routeShortName: String)
        /// The pattern is there, but no trip of it is running at anything like this time.
        case tripGone(routeShortName: String)
        /// The traveller is already at the last stop. There is no journey left to plan.
        case rideFinished(lastStopName: String)
    }

    public static func resolve(_ ride: OnboardRide, in timetable: Timetable, now: Date)
        -> Result<ResolvedOnboardRide, Failure> {
        let patterns = OnboardPatternLookup.patterns(forLine: ride.normalizedLine, in: timetable)
        guard let pattern = patterns.first(where: {
            OnboardPatternLookup.stopIDs(ofPattern: $0, in: timetable) == ride.patternStopIDs
        }) else {
            return .failure(.patternGone(routeShortName: ride.routeShortName))
        }

        let positions = timetable.stopCount(ofPattern: pattern)
        // Clamped rather than trusted: the fingerprint matched, so the length is the same, but
        // a stored position from a differently shaped predecessor must not index out of range.
        let position = min(max(ride.currentPosition, 0), positions - 1)
        guard position < positions - 1 else {
            let stop = timetable.stops[Int(timetable.stopIndex(pattern: pattern,
                                                               position: positions - 1))]
            return .failure(.rideFinished(lastStopName: stop.name))
        }

        guard let trip = trip(for: ride, pattern: pattern, position: position,
                              in: timetable) else {
            return .failure(.tripGone(routeShortName: ride.routeShortName))
        }
        return .success(ResolvedOnboardRide(
            pattern: pattern, trip: trip, currentPosition: position,
            delaySeconds: Int32(ride.observedDelaySeconds)))
    }

    /// The trip by its GTFS id when the feed still has it, otherwise the one whose schedule at
    /// this position lands closest to the schedule the ride was resolved against.
    ///
    /// The fallback is not a guess about which vehicle it is — the fingerprint already fixed
    /// the pattern and the stored `scheduledAtCurrent` fixes the hour. It exists because
    /// `trip_id` is regenerated by the operator between feeds, exactly the reason
    /// `ActiveJourneySnapshot.Ride.tripID` is documented as informative only.
    private static func trip(for ride: OnboardRide, pattern: Int, position: Int,
                             in timetable: Timetable) -> Int? {
        let count = timetable.tripCount(ofPattern: pattern)
        guard count > 0 else { return nil }
        if let tripID = ride.tripID,
           let match = (0..<count).first(where: {
               timetable.tripRef(pattern: pattern, trip: $0).tripID == tripID
           }) {
            return match
        }
        let wanted = Int32(timetable.axisSeconds(for: ride.scheduledAtCurrent))
        var best: Int?
        var bestDistance = Int32.max
        for trip in 0..<count {
            let scheduled = timetable.departure(pattern: pattern, trip: trip, position: position)
            let distance = abs(scheduled &- wanted)
            if distance < bestDistance { bestDistance = distance; best = trip }
        }
        // Half an hour. Beyond that the closest trip is a different service of the same line,
        // and riding along with its times would be a fabrication.
        return bestDistance <= 30 * 60 ? best : nil
    }
}
